import { roboto } from "@/app/fonts"
import Navbar from "../components/Navbar"
import "./globals.css"

export const metadata = {
    title: {
        default: 'Next.js Sites',
        template: '%s | Next.js Sites',
    } 
    // title: 'Next.js Sites',
    // description: 'Generated by create next app',
  }

export default function Layout({children}) {
    return (
        <>
            <html lang="en" className={roboto.className}>
                
                <body className="mx-4 my-4">
                    <header>
                        <Navbar />
                    </header>
                    <main className="my-3 min-h-screen">{children}</main>
                    <footer className="text-center grow">
                        <hr />
                        <span>Turu</span>
                    </footer>
                </body>
            </html>
        </>
    )
}